/*
 * This source file was generated by the Gradle 'init' task
 */
package shootertargeting;

import org.junit.jupiter.api.Test;

import shootertargeting.ShooterTargetingWithDrag;

class AppTest {
    @Test void appHasAGreeting() {
        ShooterTargetingWithDrag classUnderTest = new ShooterTargetingWithDrag();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
